#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Input\InputArgument;

$app = new Application('CB Command Line Application', '1.0');

$app->register('hi')
    ->setDescription('Offer a greeing to the given person')
    ->addArgument('name', InputArgument::OPTIONAL, 'Your NAme')
    ->setCode(function(InputInterface $input, OutputInterface $output)
    {
        $name = $input->getArgument('name');
        $message = 'Hello, ' . $input->getArgument('name');
        $output->writeln("<info>{$message}</info>");
    });


$app->run();